from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_student_report(student_data, file_path):

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = height - 50

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "🎓 Student Report Card")
    y -= 40

    c.setFont("Helvetica", 12)

    # Basic Info
    c.drawString(50, y, f"Name: {student_data.get('name', '')}")
    y -= 20

    c.drawString(50, y, f"Class: {student_data.get('class', '')}")
    y -= 20

    c.drawString(50, y, f"Total Marks: {student_data.get('Total', '')}")
    y -= 20

    c.drawString(50, y, f"Average: {student_data.get('Average', '')}")
    y -= 20

    c.drawString(50, y, f"Attendance: {student_data.get('attendance', '')}%")
    y -= 20

    c.drawString(50, y, f"AI Result: {student_data.get('AI_Result', '')}")
    y -= 20

    c.drawString(50, y, f"AI Score: {student_data.get('AI_Score', '')}")
    y -= 40

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Student Analytics AI System")

    c.save()
