from fpdf import FPDF
import os


def generate_student_pdf(student):

    pdf = FPDF()

    pdf.add_page()

    # =========================
    # TITLE
    # =========================
    pdf.set_font("Arial", "B", 20)

    pdf.cell(
        200,
        10,
        txt="Student Report Card",
        ln=True,
        align="C"
    )

    pdf.ln(10)

    # =========================
    # STUDENT INFO
    # =========================
    pdf.set_font("Arial", "B", 14)

    pdf.cell(200, 10, txt=f"Name: {student['name']}", ln=True)
    pdf.cell(200, 10, txt=f"Class: {student['class']}", ln=True)

    pdf.ln(5)

    # =========================
    # SUBJECT MARKS
    # =========================
    pdf.set_font("Arial", "B", 16)

    pdf.cell(200, 10, txt="Subject Marks", ln=True)

    pdf.set_font("Arial", "", 14)

    pdf.cell(200, 10, txt=f"Maths: {student['maths']}", ln=True)
    pdf.cell(200, 10, txt=f"Physics: {student['physics']}", ln=True)
    pdf.cell(200, 10, txt=f"Chemistry: {student['chemistry']}", ln=True)
    pdf.cell(200, 10, txt=f"English: {student['english']}", ln=True)

    pdf.ln(5)

    # =========================
    # PERFORMANCE
    # =========================
    pdf.set_font("Arial", "B", 16)

    pdf.cell(200, 10, txt="Performance", ln=True)

    pdf.set_font("Arial", "", 14)

    pdf.cell(
        200,
        10,
        txt=f"Attendance: {student['attendance']}%",
        ln=True
    )

    pdf.cell(
        200,
        10,
        txt=f"Average Marks: {round(student['Average'], 2)}",
        ln=True
    )

    pdf.cell(
        200,
        10,
        txt=f"AI Grade: {student['AI_Result']}",
        ln=True
    )

    pdf.ln(10)

    # =========================
    # FOOTER
    # =========================
    pdf.set_font("Arial", "I", 12)

    pdf.cell(
        200,
        10,
        txt="Generated by Student Analytics Pro",
        ln=True,
        align="C"
    )

    # =========================
    # SAVE PDF
    # =========================
    folder = "generated_reports"

    if not os.path.exists(folder):
        os.makedirs(folder)

    file_path = f"{folder}/{student['name']}_report.pdf"

    pdf.output(file_path)

    return file_path
