import streamlit as st
import sqlite3
import pandas as pd
import os

# =========================
# PDF IMPORTS
# =========================
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

from io import BytesIO


# =========================
# PDF GENERATOR
# =========================
def generate_fee_pdf(student_name, fee_data):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    # =========================
    # TITLE
    # =========================
    title = Paragraph(
        "<b>Student Fee Receipt</b>",
        styles['Title']
    )

    elements.append(title)

    elements.append(Spacer(1, 20))

    # =========================
    # STUDENT INFO
    # =========================
    info = f"""
    <b>Student Name:</b> {student_name}<br/>
    <b>Class:</b> {fee_data['class']}<br/>
    <b>Total Fees:</b> ₹{fee_data['total_fees']}<br/>
    <b>Paid Amount:</b> ₹{fee_data['paid_amount']}<br/>
    <b>Pending Amount:</b> ₹{fee_data['pending_amount']}<br/>
    <b>Due Date:</b> {fee_data['due_date']}<br/>
    <b>Status:</b> {fee_data['status']}<br/>
    """

    elements.append(
        Paragraph(info, styles['BodyText'])
    )

    elements.append(Spacer(1, 30))

    # =========================
    # FOOTER
    # =========================
    footer = Paragraph(
        "Generated by Student Analytics Pro",
        styles['Italic']
    )

    elements.append(footer)

    # BUILD PDF
    doc.build(elements)

    buffer.seek(0)

    return buffer


def fees_page():

    st.title("💳 Fees Management System")

    # =========================
    # DATABASE PATH
    # =========================
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

    db_path = os.path.join(
        BASE_DIR,
        "../database/school.db"
    )

    conn = sqlite3.connect(db_path)

    role = st.session_state.get("role")
    user = st.session_state.get("user")

    # =========================
    # ADMIN PANEL
    # =========================
    if role == "admin":

        st.subheader("➕ Add Student Fees")

        student_name = st.text_input("👨‍🎓 Student Name")

        student_class = st.text_input("🏫 Class")

        total_fees = st.number_input(
            "💰 Total Fees",
            min_value=0.0
        )

        paid_amount = st.number_input(
            "✅ Paid Amount",
            min_value=0.0
        )

        due_date = st.date_input("📅 Due Date")

        pending_amount = total_fees - paid_amount

        status = "Paid"

        if pending_amount > 0:
            status = "Pending"

        # =========================
        # SAVE FEES
        # =========================
        if st.button("💾 Save Fees"):

            cursor = conn.cursor()

            cursor.execute(
                """
                INSERT INTO fees (
                    student_name,
                    class,
                    total_fees,
                    paid_amount,
                    pending_amount,
                    due_date,
                    status
                )

                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    student_name,
                    student_class,
                    total_fees,
                    paid_amount,
                    pending_amount,
                    str(due_date),
                    status
                )
            )

            conn.commit()

            st.success("✅ Fees Added Successfully")

    st.divider()

    # =========================
    # SHOW FEES DATA
    # =========================
    st.subheader("📄 Fees Records")

    query = """
    SELECT * FROM fees
    ORDER BY id DESC
    """

    df = pd.read_sql_query(query, conn)

    conn.close()

    # =========================
    # EMPTY CHECK
    # =========================
    if df.empty:

        st.warning("No fees records found")

        return

    # =========================
    # STUDENT VIEW
    # =========================
    if role == "student":

        df = df[
            df["student_name"].str.lower()
            ==
            str(user).lower()
        ]

    # =========================
    # DISPLAY DATA
    # =========================
    st.dataframe(
        df,
        use_container_width=True
    )

    # =========================
    # PDF DOWNLOAD
    # =========================
    st.subheader("🧾 Fee Receipt PDF Download")

    for _, row in df.iterrows():

        pdf = generate_fee_pdf(
            row["student_name"],
            row
        )

        st.download_button(
            label=f"📥 Download Receipt - {row['student_name']}",
            data=pdf,
            file_name=f"{row['student_name']}_fee_receipt.pdf",
            mime="application/pdf"
        )

    # =========================
    # FEES SUMMARY
    # =========================
    st.subheader("📊 Fees Analytics")

    total_collection = df["paid_amount"].sum()

    pending_collection = df["pending_amount"].sum()

    col1, col2 = st.columns(2)

    col1.metric(
        "💰 Total Collection",
        f"₹ {total_collection}"
    )

    col2.metric(
        "⚠ Pending Fees",
        f"₹ {pending_collection}"
    )
